import type { Metadata } from 'next'
import './globals.css'
import { Inter as FontSans } from "next/font/google"
import Provider from '@/utils/Providers'
import { cn } from "../lib/utils"
import { Toaster } from "@/components/ui/toaster"
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/*<body className={inter.className}>*/}
    <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Provider>
        {children}
        </Provider>
        <Toaster />
      </body>
    </html>
  )
}
